import test from 'node:test';import assert from 'node:assert/strict';
import {applyTemporalResult,enhanceSequence} from '../src/temporal.js';import {jointReliable,alignToImage,poseAt} from '../src/core.js';
const frame=t=>({t,screen:Array.from({length:33},()=>[.5,.5,1]),points:Array.from({length:33},()=>[0,0,0]),issue:null});
const result=n=>({source:'motionbert',supported:[7,8,11,12,13,14,15,16,23,24,25,26,27,28],points:Array.from({length:n},()=>Array.from({length:33},(_,i)=>[i*.01,.1,.2]))});
test('sequence inference cannot restore missing observations or raise their confidence',()=>{const frames=[frame(0),{...frame(1),screen:null,points:null,issue:'missing'},frame(2)];frames[0].screen[15][2]=.2;const enhanced=applyTemporalResult(frames,result(3));assert.equal(enhanced[1].points,null);assert.equal(enhanced[0].screen[15][2],.2);assert.equal(jointReliable(enhanced[0],15),false);assert.deepEqual(frames[0].points[11],[0,0,0]);});
test('unpredicted feet and fingers are hidden while model coordinates survive image alignment and interpolation',()=>{const enhanced=applyTemporalResult([frame(0),frame(1)],result(2));assert.equal(jointReliable(enhanced[0],29),false);assert.equal(jointReliable(enhanced[0],27),true);assert.equal(alignToImage(enhanced[0],.5),enhanced[0]);const p=poseAt(.5,enhanced);assert.equal(p.source,'motionbert');assert.equal(jointReliable(p,29),false);});
test('mismatched and nonfinite model responses are rejected',()=>{assert.throws(()=>applyTemporalResult([frame(0)],result(2)));const bad=result(1);bad.points[0][11][2]=NaN;assert.throws(()=>applyTemporalResult([frame(0)],bad));});
test('worker failure preserves a useful error and cancels the local job',async()=>{const requests=[];const fetch=async(url)=>{requests.push(url);const data=url==='./api/motion'?requests.length===1?{available:true}:{id:'local-job'}:url.includes('/job')?{status:'error',error:'模型错误'}:{status:'cancelled'};return {ok:true,json:async()=>data};};await assert.rejects(()=>enhanceSequence({},new AbortController().signal,null,fetch),/模型错误/);assert.equal(requests.at(-1),'./api/motion/cancel');});
test('successful job returns its result without starting a second inference',async()=>{let n=0;const fetch=async(url)=>{n++;return {ok:true,json:async()=>url==='./api/motion'?n===1?{available:true}:{id:'one'}:url.includes('/job')?{status:'done',result:result(1)}:{status:'cancelled'}};};assert.equal((await enhanceSequence({},new AbortController().signal,null,fetch)).source,'motionbert');assert.equal(n,4);});
